:sparkles: new ci

diff --git a/.github/workflows/Release.yml b/.github/workflows/Release.yml
--- a/.github/workflows/Release.yml
+++ b/.github/workflows/Release.yml
@@ -54,36 +54,26 @@ jobs:
           if [ "$RELEASE" == "NOT_FOUND" ]; then
             echo "Release does not exist. Creating release $VERSION."
             gh release create $VERSION -F ci/version.info.txt --target ${{ github.sha }}
-            matrix='['
-            for key in "${!host_dict[@]}"; do
-              if [ "$key" != "${!host_dict[@]: -1}" ]; then
-                matrix+="{\"target\": \"$key\", \"host\": \"${host_dict[$key]}\"},"
-              else
-                matrix+="{\"target\": \"$key\", \"host\": \"${host_dict[$key]}\"}"
-              fi
-            done
-            matrix+=']'
-            echo "matrix='$matrix'" >> $GITHUB_OUTPUT
           else
             echo "Release $VERSION already exists."
-            gh release view $VERSION --json assets > release_assets.json
-            echo release_assets.json :
-            cat release_assets.json
-            matrix='['
-            for key in "${!asset_dict[@]}"; do
-              asset_name=${asset_dict[$key]}
-              asset_exists=$(gh release view $VERSION --json assets -q ".assets[].name" | grep -w "$asset_name" || echo "NOT_FOUND")
-              if [ "$asset_exists" == "NOT_FOUND" ]; then
-                echo "Asset $asset_name does not exist. Upload is required."
-                matrix+="{\"target\": \"$key\", \"host\": \"${host_dict[$key]}\"},"
-              else
-                echo "Asset $asset_name already exists. No upload is required."
-              fi
-            done
-            matrix=${matrix%,} # Remove trailing comma
-            matrix+=']'
-            echo "matrix='$matrix'" >> $GITHUB_OUTPUT
           fi
+          gh release view $VERSION --json assets > release_assets.json
+          echo release_assets.json :
+          cat release_assets.json
+          matrix='['
+          for key in "${!asset_dict[@]}"; do
+            asset_name=${asset_dict[$key]}
+            asset_exists=$(gh release view $VERSION --json assets -q ".assets[].name" | grep -w "$asset_name" || echo "NOT_FOUND")
+            if [ "$asset_exists" == "NOT_FOUND" ]; then
+              echo "Asset $asset_name does not exist. Upload is required."
+              matrix+="{\"target\": \"$key\", \"host\": \"${host_dict[$key]}\"},"
+            else
+              echo "Asset $asset_name already exists. No upload is required."
+            fi
+          done
+          matrix=${matrix%,} # Remove trailing comma
+          matrix+=']'
+          echo "matrix='$matrix'" >> $GITHUB_OUTPUT
           echo "GITHUB_OUTPUT : $GITHUB_OUTPUT :"
           cat $GITHUB_OUTPUT
 
